name: fixli_app
description: Fixli – din lokala hjälpapp.
publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Arkitektur & State Management
  flutter_riverpod: ^2.5.1
  get_it: ^7.6.7
  equatable: ^2.0.5
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1

  # Lokal Databas (Drift)
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.2
  path: ^1.9.0
  url_launcher: ^6.2.5

  # Säkerhet & Verktyg
  bcrypt: ^1.1.3
  uuid: ^4.3.3
  intl: ^0.19.0
  share_plus: ^7.2.1
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  grouped_list: ^5.1.2
  flutter_boring_avatars: ^2.0.1
  timeago: ^3.6.1
  flutter_slidable: ^3.1.0
  haversine_distance: ^1.2.1
  shared_preferences: ^2.2.3
  introduction_screen: ^3.1.14
  photo_view: ^0.15.0
  smooth_page_indicator: ^1.1.0 # För sidindikatorerna
  cloud_firestore: ^4.17.4

  # Paket för kartan
  google_maps_flutter: ^2.5.3  # <-- DET ÄR DENNA RAD SOM SKA VARA RÄTT
  geocoding: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Kodgenerering för Drift
  drift_dev: ^2.14.0
  build_runner: ^2.4.8

  flutter_launcher_icons: ^0.13.1


# 🟢 Konfigurationen ska ligga här, på rot-nivå (samma nivå som 'flutter:')
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/fixli_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/fixli_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/fixli_logo.png
    - assets/fixli_icon.png
    - assets/illustrations/
    - assets/